version: '3'

services:
  webfrontend:
    image: webfrontend
    build:
      context: .
      dockerfile: ../WebFrontEnd/Dockerfile
    depends_on:
      - "services"
  services:
    image: services
    build:
      context: .
      dockerfile: Services/Dockerfile

