version: '3'

services:
  webfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

